repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog Secrets Scan (Latest Commit)
        description: Detects secrets in staged changes for a fast check.
        entry:  bash -c 'git diff --cached --name-only | xargs trufflehog filesystem --no-verification --fail --include-detectors=all'
        language: system
        stages: [commit]
