repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog Secrets Scan (Latest Commit)
        description: Detects secrets in staged changes for a fast check.
        entry: bash -c 'TRUFFLEHOG_DISABLE_UPDATE_CHECK=true trufflehog git file://. --since-commit HEAD^ --no-verification --fail --no-update'
        language: system
        stages: [commit]
