name: CD Pipeline

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: sdg8193_rekor

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF_NAME}
          CLEAN_VERSION=${VERSION#v}
          echo "PACKAGE_VERSION=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --no-interaction --with dev

      - name: Build Package
        run: poetry build

      - name: Generate CycloneDX SBOM
        id: generate_sbom
        run: |
          pip install cyclonedx-bom
          SBOM_FILE="dist/sbom-${{ steps.get_version.outputs.PACKAGE_VERSION }}.cdx.json"
          cyclonedx-py poetry > "$SBOM_FILE"
          echo "SBOM_PATH=$SBOM_FILE" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ steps.get_version.outputs.PACKAGE_VERSION }}"
          files: |
            dist/*.whl
            dist/*.tar.gz
            ${{ steps.generate_sbom.outputs.SBOM_PATH }}

      - name: Attest SBOM
        uses: actions/attest-sbom@v1
        with:
          subject-path: |
            dist/*.whl
            dist/*.tar.gz
          sbom-path: ${{ steps.generate_sbom.outputs.SBOM_PATH }}

      - name: Upload Attestation File
        uses: actions/upload-artifact@v4
        with:
          name: sbom-attestation
          path: .github/attestations/

